name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest # Aqui se ejecutan todos los pasos

    steps:
    - name: Checkout code # Toma lo que tenemos en nuestro repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Para que vaya bien adentro en la busqued de nuestro historial de commits.


    #  Autenticacion en DockerHub --> Generamos un nuevo token y ejecutamos el codigo con el usuario y ese token
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


      # '|' caracter que representa una tuberia. 
      # Usualmente se lo usa cuando queremos trabajar con mas de una linea de codigo. Significa que cada una 
      # de las lineas siguientes son lineas independientes que se ingresan manualmente en la consola.
      # Lo dejamos de onda
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: |
        docker build -t mbraian/docker-graphql:0.0.2 .
        docker build -t mbraian/docker-graphql:latest .


    - name: Push Docker Image
      run: |
        docker push mbraian/docker-graphql:0.0.2
        docker push mbraian/docker-graphql:latest





