name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest # Aqui se ejecutan todos los pasos

    steps:
    - name: Checkout code # Toma lo que tenemos en nuestro repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Para que vaya bien adentro en la busqued de nuestro historial de commits.


    # =================================    Versionamiento Semántico    ==============================================================
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:" # Si se encuentra esto en alguna parte del commit, se hara una nueva version major
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}" # Cada vez que sea llamada esta accion va a ir incrementando esto
      id: version


    #  Autenticacion en DockerHub --> Generamos un nuevo token y ejecutamos el codigo con el usuario y ese token
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        # '|' caracter que representa una tuberia. 
        # Usualmente se lo usa cuando queremos trabajar con mas de una linea de codigo. Significa que cada una 
        # de las lineas siguientes son lineas independientes que se ingresan manualmente en la consola.
        # Lo dejamos de onda
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

        echo "New version: $NEW_VERSION <==================================================="

    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }} # Saca un ARRAY de diferentes valores; en este caso la version

      run: |
        docker build -t mbraian/docker-graphql:$NEW_VERSION .
        docker build -t mbraian/docker-graphql:latest .


    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }} # Saca un ARRAY de diferentes valores; en este caso la version
      run: |
        docker push mbraian/docker-graphql:$NEW_VERSION
        docker push mbraian/docker-graphql:latest





